{
  "props": [],
  "components": {
    "saveectp": {
      "type": "script\\FileChooserScript",
      "x": 288,
      "y": 64,
      "props": {
        "saveDialog": true,
        "initialDirectory": "./",
        "filterName": "Encoded Characters To Pixels",
        "filterExtensions": "*.ectp",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": "save"
      }
    },
    "openctpn": {
      "type": "script\\FileChooserScript",
      "x": 176,
      "y": 64,
      "props": {
        "filterName": "Characters To Pixels Notation",
        "filterExtensions": "*.ctpn",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": "usecustom"
      }
    },
    "openectp": {
      "type": "script\\FileChooserScript",
      "x": 64,
      "y": 64,
      "props": {
        "initialDirectory": "./",
        "filterName": "Encoded Characters To Pixels",
        "filterExtensions": "*.ectp",
        "filterAny": "0",
        "inputNode": "",
        "actionNode": "open"
      }
    }
  }
}