remote_theme: pmarsceill/just-the-docs
footer_content: "Copyright &copy; 2019 yaBobJonez (ya_Bob_Jonez). Distributed by a <a href=\"https://github.com/yaBobJonez/CtPI/blob/master/LICENSE\">DERL License.</a>"
